services:
  server:
    image: itzg/minecraft-bedrock-server:2024.11.0
    environment:
      EULA: "true"
    ports:
      - "19132:19132/udp"
    volumes:
      - store:/data

  dnsmasq:
    image: 4km3/dnsmasq:2.90-r3-alpine-latest
    hostname: dnsmasq
    networks:
      macvlan:
        ipv4_address: 192.168.86.53
    extra_hosts:
      - "host.docker.internal:host-gateway"
      - "mco.lbsg.net:192.168.86.100"
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    cap_add:
      - NET_ADMIN
      - NET_BIND_SERVICE

volumes:
  store:

networks:
  macvlan:
    external: true
    name: macvlan
